config/routes.rb
Rails.application.routes.draw do
  root 'drinks#index'
  devise_for :users

  resources :drinks, only: [:index, :new, :create, :destroy]
  get '/featured-drinks', to: 'featured_drinks#index'

  resources :categories, only: [:index, :show] do
    get 'drinks', to: 'categories#show'
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :drinks,
    dependent: :nullify

  validates :name,
    presence: true,
    uniqueness: true
end

app/models/drink.rb
class Drink < ActiveRecord::Base
  ALCOHOL_LEVELS = [
    "Low",
    "Medium",
    "High"
  ]

  belongs_to :category

  validates :title,
    presence: true,
    uniqueness: true,
    length: { minimum: 5 }

  validates :alcohol_level,
    inclusion: { in: ALCOHOL_LEVELS, allow_blank: true }

  class << self
    def featured
      where(featured: true)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @categories = Category.find(params[:category_id])
    @drinks = Drink.where("category_id = #{params[:category_id]}")
  end

end

app/controllers/drinks_controller.rb
class DrinksController < ApplicationController

  def index
    @drinks = Drink.page(params[:page])
  end

  def new
    @drink = Drink.new
  end

  def create
    @drink = Drink.new(drink_params)
    if @drink.save
      flash[:notice] = 'Drink added.'
      redirect_to drinks_path
    else
      render :new
    end
  end

  def destroy
    Drink.destroy(params[:id])
    flash[:notice] = "Drink deleted."
    redirect_to drinks_path
  end

  protected
  def drink_params
    params.require(:drink).permit(:title, :description, :category_id)
  end
end

app/controllers/featured_drinks_controller.rb
class FeaturedDrinksController < ApplicationController
  def index
    @drinks = Drinks.featured.page
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/helpers/drinks_helper.rb
module DrinksHelper
end

app/views/categories/index.html.erb
<div class="row">
  <div class="large-12">
    <h1>Categories</h1>


      <%= link_to 'Create a Drink', new_drink_path %>
      <%= paginate @drinks %>
    <%- end -%>
  </div>
</div>

app/views/categories/show.html.erb
<div class="row">
  <div class="large-12">
    <h1>Drinks for category: <%= @categories.name %></h1>

    <div>
      <ul>
        <% @drinks.each do |drink| %>
        <li><%= drink.title %></li>
        <% end %>
      </ul>
    </div>


      <%= link_to 'Create a Drink', new_drink_path %>
  </div>
</div>

app/views/drinks/index.html.erb
<div class="row">
  <div class="large-12">
    <h1>Drinks</h1>

    <%- if !@drinks.empty? -%>
      <table>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Category</th>
          <th></th>
        </tr>

        <%- @drinks.each do |drink| -%>
          <tr>
            <td><%= drink.title %></td>
            <td><%= truncate(drink.description, length: 30) %></td>
            <td><%= drink.category_id %></td>
            <td>
              <%= link_to 'Delete',
                '/drinks/' + drink.to_param,
                method: :delete %>
            </td>
          </tr>
        <%- end -%>
      </table>

      <%= link_to 'Create a Drink', new_drink_path %>
      <%= paginate @drinks %>
    <%- end -%>
  </div>
</div>

app/views/drinks/new.html.erb
<div class="row">
  <%- if @drink.errors.present? -%>
    <div class="large-12 alert-box alert" data-alert>
      <ul>
        <%- @drink.errors.full_messages.each do |error| -%>
          <li><%= error %></li>
        <%- end -%>
      </ul>
    </div>
  <%- end -%>

  <div class="large-12">
    <h1>New Drink</h1>

    <%= form_for @drink do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.check_box :featured %>
      <%= f.label :featured %>
      </br>

      <%= f.select :category, Category.all.map { |c| [c.name, c.id] } %>
      <%= f.label :category %>

      <%= f.radio_button(:alcohol_level, "Low", id: "Low") %>
      <%= f.label(:low) %>

      <%= f.radio_button(:alcohol_level, "Medium", id: "Medium") %>
      <%= f.label(:medium) %>

      <%= f.radio_button(:alcohol_level, "High", id: "High") %>
      <%= f.label(:high) %>
    </br>



      <%= f.submit "Add Drink" %>
    <%- end -%>

    </br>
    <%= link_to "Drinks List", drinks_path %>
  </div>
</div>

app/views/featured_drinks/index.html.erb
<div class="row">
  <div class="large-12">
    <h1>Featured Drinks</h1>

    <%- if !@drinks.empty? -%>
      <table>
        <tr>
          <th>Title</th>
          <th>Description</th>
        </tr>

        <%- @drinks.each do |drink| -%>
          <tr>
            <td><%= drink.title %></td>
            <td><%= drink.description.truncate(30) %></td>
          </tr>
        <%- end -%>
      </table>

      <% link_to 'See all drinks', drinks_path %>
      <%= paginate @drinks %>
    <%- end -%>
  </div>
</div>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Launchtails</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">Launchtails</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>